### ISSUE TITLE
Potential feature ideas

### ISSUE THREAD

**Issue by AustinZM** [ckosidow/prestige-levelling#1]
Would a toggle to hide true level be possible unless it is the next level you'll receive? I.E instead of 94/86 it will instead show 86/86.

Is it possible to interact with the default XP Globes plugin in any way to influence the data it's pulling from and replace it with Prestige's data?

The first suggestion would allow for compatibility with the boosts information plugin with relative boosts as well. Currently, Prestige bricks it a bit.

Thank you for your time in reading this, and thank you for making this plugin <3

**Comment by kevinturtle** [comment]
On top of this, it would be nice to be able to set another level at which you can prestige. e.g. I would rather prestige 10 times at level 76.

**Comment by ckosidow** [comment]
I'll try to figure this one out. I'd consider it kind of a bug. Need to read more about how this level is displayed.

**Comment by ckosidow** [comment]
This fix has been pushed in https://github.com/runelite/plugin-hub/pull/4590. Boosts should now display correctly
