### ISSUE TITLE
Add a toggle to disable this for HP stat

### ISSUE THREAD

**Issue by horse4lunch** [ckosidow/prestige-levelling#2]
Even though the number still shows the correct 92 hp. It messes with status bars/the fill amount on the hp data orb. So they will appear full even when they arent.

**Comment by ckosidow** [comment]
This should be addressed in the latest PR: https://github.com/runelite/plugin-hub/pull/4519

I've added the ability to disable prestige for HP, prayer, combat and non-combat skills. A better solution may come in the future, but for now you should be able to keep the plugin on and disable HP prestige.
