### ISSUE TITLE
Post 99 Prestige?

### ISSUE THREAD

**Issue by Allifreyr** [ckosidow/prestige-levelling#4]
Would be a cool option, for those of us that are going for goals beyond 99 :)

Also having the option to tweak the exp multiplier (from 2x to 3x for example) for post 99? This one is a secondary idea/request, the other one would be better if I had to choose between them.

**Comment by ckosidow** [comment]
https://github.com/runelite/plugin-hub/pull/4590 - should address the level goal. It should be configurable now up to level 126.

**Comment by Allifreyr** [comment]
Sweet, thanks! Didn't expect such a quick response from you 😄

Now I'm that much more motivated to keep on the grind! 💪

**Comment by ckosidow** [comment]
Update: Added the xp factor, so now you can configure between 2 and 100.

The factor will reset your level at **goal xp - (1 / xp factor)**. So if you have it set to 100, you'll need 1/100th of the xp for your goal to prestige and your xp will be multiplied by 100 thereafter.

Eventually this should probably be configured per skill group (combat, non-combat, hp, prayer) but that's a future thing if someone wants it.

**Comment by Allifreyr** [comment]
Sweet! Wasn't expecting for you to do both of the suggestions 😄 

Configured per skill would be really cool, other than that, the plugin feels very complete and amazing
